// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TSD2491_OBLIG1_249954.Data;

#nullable disable

namespace TSD2491_OBLIG1_249954.Migrations
{
    [DbContext(typeof(BrukerContext))]
    [Migration("20250330182302_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("TSD2491_oblig_1_studentnr.Models.Bruker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AntallSpill")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KontaktInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Bruker");
                });
#pragma warning restore 612, 618
        }
    }
}
